vpaths
{
  ["Core"] =
  {
    "D:/dev/projects/BSR/Engine/src/Application.cpp",
    "D:/dev/projects/BSR/Engine/src/Application.h",
    "D:/dev/projects/BSR/Engine/src/Engine.h",
    "D:/dev/projects/BSR/Engine/src/EntryPoint.h",
    "D:/dev/projects/BSR/Engine/src/InputCodes.h",
    "D:/dev/projects/BSR/Engine/src/Options.h"
  },
  ["Renderer"] =
  {
    "D:/dev/projects/BSR/Engine/src/Buffer.cpp",
    "D:/dev/projects/BSR/Engine/src/Buffer.h",
    "D:/dev/projects/BSR/Engine/src/Material.cpp",
    "D:/dev/projects/BSR/Engine/src/Material.h",
    "D:/dev/projects/BSR/Engine/src/OpenGLContext.cpp",
    "D:/dev/projects/BSR/Engine/src/OpenGLContext.h",
    "D:/dev/projects/BSR/Engine/src/RenderCommandQueue.cpp",
    "D:/dev/projects/BSR/Engine/src/RenderCommandQueue.h",
    "D:/dev/projects/BSR/Engine/src/Renderer.cpp",
    "D:/dev/projects/BSR/Engine/src/Renderer.h",
    "D:/dev/projects/BSR/Engine/src/RendererAPI.cpp",
    "D:/dev/projects/BSR/Engine/src/RendererAPI.h",
    "D:/dev/projects/BSR/Engine/src/RenderState.cpp",
    "D:/dev/projects/BSR/Engine/src/RenderState.h",
    "D:/dev/projects/BSR/Engine/src/Shader.cpp",
    "D:/dev/projects/BSR/Engine/src/Shader.h",
    "D:/dev/projects/BSR/Engine/src/ShaderUniform.cpp",
    "D:/dev/projects/BSR/Engine/src/ShaderUniform.h",
    "D:/dev/projects/BSR/Engine/src/ShaderUtils.cpp",
    "D:/dev/projects/BSR/Engine/src/ShaderUtils.h",
    "D:/dev/projects/BSR/Engine/src/Texture.h",
    "D:/dev/projects/BSR/Engine/src/VertexArray.cpp",
    "D:/dev/projects/BSR/Engine/src/VertexArray.h"
  },
  ["Messages"] =
  {
    "D:/dev/projects/BSR/Engine/src/EngineMessages.h",
    "D:/dev/projects/BSR/Engine/src/Message.cpp",
    "D:/dev/projects/BSR/Engine/src/Message.h",
    "D:/dev/projects/BSR/Engine/src/MessageBus.cpp",
    "D:/dev/projects/BSR/Engine/src/MessageBus.h",
    "D:/dev/projects/BSR/Engine/src/MessageHandler.h"
  },
  ["Framework"] =
  {
    "D:/dev/projects/BSR/Engine/src/Framework.cpp",
    "D:/dev/projects/BSR/Engine/src/Framework.h",
    "D:/dev/projects/BSR/Engine/src/SDLEventPoller.cpp",
    "D:/dev/projects/BSR/Engine/src/SDLMouseController.cpp",
    "D:/dev/projects/BSR/Engine/src/SDLWindow.cpp"
  },
  ["Interface"] =
  {
    "D:/dev/projects/BSR/Engine/src/IEventPoller.h",
    "D:/dev/projects/BSR/Engine/src/IGraphicsContext.h",
    "D:/dev/projects/BSR/Engine/src/IMouseController.h",
    "D:/dev/projects/BSR/Engine/src/IWindow.h"
  },
  ["ImGui"] =
  {
    "D:/dev/projects/BSR/Engine/src/imgui_impl_opengl3.cpp",
    "D:/dev/projects/BSR/Engine/src/imgui_impl_opengl3.h"
  },
  ["Layers"] =
  {
    "D:/dev/projects/BSR/Engine/src/Layer.h",
    "D:/dev/projects/BSR/Engine/src/LayerStack.cpp",
    "D:/dev/projects/BSR/Engine/src/LayerStack.h",
    "D:/dev/projects/BSR/Engine/src/Layer_Application.cpp",
    "D:/dev/projects/BSR/Engine/src/Layer_Application.h",
    "D:/dev/projects/BSR/Engine/src/Layer_Console.cpp",
    "D:/dev/projects/BSR/Engine/src/Layer_Console.h",
    "D:/dev/projects/BSR/Engine/src/Layer_imgui.cpp",
    "D:/dev/projects/BSR/Engine/src/Layer_imgui.h",
    "D:/dev/projects/BSR/Engine/src/Layer_InputHandler.cpp",
    "D:/dev/projects/BSR/Engine/src/Layer_InputHandler.h",
    "D:/dev/projects/BSR/Engine/src/Layer_Window.cpp",
    "D:/dev/projects/BSR/Engine/src/Layer_Window.h"
  },
  ["Memory"] =
  {
    "D:/dev/projects/BSR/Engine/src/Memory.cpp",
    "D:/dev/projects/BSR/Engine/src/Memory.h",
    "D:/dev/projects/BSR/Engine/src/Resource.h",
    "D:/dev/projects/BSR/Engine/src/ResourceID.cpp",
    "D:/dev/projects/BSR/Engine/src/ResourceID.h",
    "D:/dev/projects/BSR/Engine/src/ResourceManager.cpp",
    "D:/dev/projects/BSR/Engine/src/ResourceManager.h"
  },
  ["Renderer/RenderThread"] =
  {
    "D:/dev/projects/BSR/Engine/src/RenderThread.cpp",
    "D:/dev/projects/BSR/Engine/src/RenderThread.h",
    "D:/dev/projects/BSR/Engine/src/RenderThreadData.cpp",
    "D:/dev/projects/BSR/Engine/src/RenderThreadData.h",
    "D:/dev/projects/BSR/Engine/src/RT_BindingPoint.cpp",
    "D:/dev/projects/BSR/Engine/src/RT_BindingPoint.h",
    "D:/dev/projects/BSR/Engine/src/RT_Buffer.cpp",
    "D:/dev/projects/BSR/Engine/src/RT_Buffer.h",
    "D:/dev/projects/BSR/Engine/src/RT_RendererProgram.cpp",
    "D:/dev/projects/BSR/Engine/src/RT_RendererProgram.h",
    "D:/dev/projects/BSR/Engine/src/RT_VertexArray.cpp",
    "D:/dev/projects/BSR/Engine/src/RT_VertexArray.h"
  }
}